### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by 0xspade** [xnl-h4ck3r/GAP-Burp-Extension#7]
I saw in the bottom picture of this tool that it has a generated query string of all parameters, is it possible that it also appends in the URL as you browse or at least check for it's reflection?

I'm thinking a way if it is possible to combine with this [tool](https://github.com/elkokc/reflector).

**Comment by xnl-h4ck3r** [comment]
HI @0xspade . Thanks for taking the time to use GAP and raise an issue. I'll look into that and get back to you! Thanks

**Comment by xnl-h4ck3r** [comment]
Hi @0xspade. I've looked into this, but I don't think I'll be able to do that. GAP only gathers parameters and links when you run it because there is quite a lot of post processing needed to get those, and also to ensure not a million duplicates, etc. So it doesn't gather info as you use it.
Also, the concatenated query string of parameters can quicly get huge which can cause problems because of length of the URL. It's probably better to use separate extensions to help with this. 
Also, in GAP v2.0 I removed the concatenated parameter query string because of it's limited use, but I will probably add that back in again soon!
Thanks
Xnl
